apiVersion: v1
kind: Service
metadata:
  name: items-kube-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: items-kube
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000